CREATE TABLE users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36),
  openid VARCHAR(255),
  unionid VARCHAR(255),
  name VARCHAR(255),
  created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
